👻 permit empty expressions
this commit addresses crashes that look like so, reproducible on 218b40c:

```
; cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/j`

thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', src/r.rs:35:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

...and, after this change:

```
; cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/j`

  1 + 2
3
```

most importantly, `j::eval` will not return `Ok(None)` when given an
empty input string. a new `rrn!` macro is added to the project prelude
in order to return `Ok(None)`.

a debug assertion in `j::r::parse` is now guarded behind a check that
the string is not only empty whitespace.